[package]
name = "trane-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
chrono = "0.4"
clap = { version = "3.1.18", features = ["derive"] }
rustyline = "9.1.2"
termimad = "0.14"
# trane = { git = "ssh://git@github.com/martinmr/trane.git" }
trane = { path = "../trane" }